### ISSUE TITLE
Should it check for python3-numpy instead of numpy or python-numpy ?

### ISSUE THREAD

**Issue by waterwin** [jks-prv/kiwiclient#108]
Dependencies
Make sure the Python package 'numpy' is installed. On many Linux distributions the command would be similar to 'apt install python-numpy'

Although python3-numpy is installed on my Ubuntu 2104 system the install used by wsprdaemon misses numpy when checking the kiwirecorder dependencies.

The latest command should be 'apt install python3-numpy'

**Comment by jks-prv** [comment]
Fixed
