### ISSUE TITLE
Working with kiwiwfrecorder waterfall data

### ISSUE THREAD

**Issue by doccodyblue** [jks-prv/kiwiclient#126]
Is there an example for reading .npy generated by kiwiwfrecorder?

I understand that there is a kind of "header" with the bin frequencies. Thats followed by ts and the wf data for each line
(According to #77 )

np.load returns a singe array containing the bin frequencies. But how do I fetch the wf data?

Is reading the waterfall npy done in any other related code where I could have a look?

Regards,
Andy

**Comment by hcab14** [comment]
This should work:

```python
with open(npy_filename,'rb') as f:
     wf_bins = np.load(f)
     wf_data = np.load(f)
```

**Comment by doccodyblue** [comment]
I didn't expect it to be that simple :)

Thank you!
