### ISSUE TITLE
Could kiwirecorder be easily enhanced to accept stdin as the audio source  rather than a Kiwi?

### ISSUE THREAD

**Issue by rrobinett** [jks-prv/kiwiclient#127]
In order for wsprdaemon to record spots on VHF/UHF bands it would be easiest if there were a utility which mimics KWR's --dt-sec behavior with a KiwiSDR as its source when a baseband audio would be KWR's source for audio samples.  
Not being a python programmer, it is unclear to me if KWR could be easily modified for that purpose.

**Comment by hcab14** [comment]
It might be simpler to use `sox` (see https://linux.die.net/man/1/sox), _i.e._, you might use something like this 
```
sox infile.wav output.wav trim 0 30 : newfile : restart
```
and replace `infile.wav` with std input (+ the necessary options to make `sox` understand the format of the the input samples)

**Comment by rrobinett** [comment]
Audio input is no longer a requirement for wsprdaemon, so this is no longer needed
