### ISSUE TITLE
kiwiwfrecorder seems obsolete....

### ISSUE THREAD

**Issue by frohro** [jks-prv/kiwiclient#142]
Hi,

I was delighted to find kiwirecorder this afternoon.  It will be a big help with a project I'm working on.  In the process, I saw kiwiwfrecorder, and did:
```
python3 kiwiwfrecorder.py -h
Usage: kiwiwfrecorder.py [options]

Options:
  -h, --help            show this help message and exit
  -s SERVER_HOST, --server-host=SERVER_HOST
                        Server host
  -p SERVER_PORT, --server-port=SERVER_PORT
                        Server port, default 8073
  --pw=PASSWORD, --password=PASSWORD
                        Kiwi login password
  --tlimit-pw=TLIMIT_PASSWORD, --tlimit-password=TLIMIT_PASSWORD
                        Connect time limit exemption password (if required)
  -u USER, --user=USER  Kiwi connection user name
  -f FREQUENCY, --freq=FREQUENCY
                        Frequency to tune to, in kHz
  -z ZOOM, --zoom=ZOOM  Zoom level 0-14
  --station=STATION     Station ID to be appended to filename
  --log=LOG_LEVEL, --log-level=LOG_LEVEL, --log_level=LOG_LEVEL
                        Log level: debug|info|warn(default)|error|critical
```
This was helpful, but then I found that kiwirecorder seems to have surpassed kiwiwfrecorder, and the docs are way better.  This was not apparent to me from the README, and at first kiwiwfrecorder seemed like more what I wanted.  Then I read issue #119 from 2022 that kiwiwfrecorder was going to become obsolete.   It now seems to have happened.  Am I correct?  If so, could we have some more obvious notes in the README?

Another thing I noted:  Python3 is advised now, which is great, but the example .ipynb has not been updated.  I would really appreciate that myself.  :-)

Thanks for this very handy software to query kiwisdr receivers!

Rob
KL7NA

**Comment by jks-prv** [comment]
kiwiwfrecorder is not obsolete. It's just a specialty program (as described in the README file) that only records data to .npy files. I believe it was developed before the waterfall capabilities were added to kiwirecorder.

I have been intending in folding the functionality of kiwiwfrecorder into kiwirecorder. But this is very low priority as I don't believe anyone (except for Christoph) uses it much.

The IS0KYB "micro tools" were written by, well, IS0KYB. I know about microkiwi_waterfall.py but not about the other stuff.

**Comment by frohro** [comment]
Thanks!
Rob

**Comment by frohro** [comment]
Thanks!
Rob
