### ISSUE TITLE
chunk depricated 

### ISSUE THREAD

**Issue by bminish** [jks-prv/kiwiclient#147]
Fedora linux 41 ships with python 3.13.0
This breaks kiwiclinet as this version of python deprecates the builtin 'chunk' which 
 /kiwiclient/kiwi/wavreader.py depends on 
 
 See here for the Python notice about Chunk 

 
 https://docs.python.org/3/whatsnew/3.13.html#whatsnew313-pep594

python3 -u kiwirecorder.py --help
Traceback (most recent call last):
  File "/home/bminish/kiwisdr/kiwiclient/kiwirecorder.py", line 17, in <module>
    from kiwi import KiwiSDRStream, KiwiWorker
  File "/home/bminish/kiwisdr/kiwiclient/kiwi/__init__.py", line 8, in <module>
    from .wavreader import *
  File "/home/bminish/kiwisdr/kiwiclient/kiwi/wavreader.py", line 9, in <module>
    from chunk import Chunk
ModuleNotFoundError: No module named 'chunk'
make: *** [Makefile:579: help] Error 1

bminish@redbox:~/kiwisdr/kiwiclient$ python --version
Python 3.13.0
bminish@redbox:~/kiwisdr/kiwiclient$ cat /etc/redhat-release 
Fedora release 41 (Forty One)

**Comment by jks-prv** [comment]
Okay, thanks. Please give the fix I just checked-in a try.

**Comment by bminish** [comment]
Thank you, this has resolved the issue
