### ISSUE TITLE
kiwiclientd and python3

### ISSUE THREAD

**Issue by helioshk** [jks-prv/kiwiclient#88]
Hi,
This ran well with python2, which is no longer supported in debian bullseye. So I assume it is a python3 compatibility issue, perhaps you or @rikvanriel have a tip how to solve this?
```
 ./kiwiclientd.py 
Traceback (most recent call last):
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 427, in <module>
    main()
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 401, in main
    snd_recorders.append(KiwiWorker(args=(KiwiSoundRecorder(opt),opt,run_event)))
  File "/home/helios/git/kiwiclient/kiwi/worker.py", line 18, in __init__
    self._rigctld = Rigctld(self._recorder, self._options.rigctl_port, self._options.rigctl_address)
  File "/home/helios/git/kiwiclient/kiwi/rigctld.py", line 75, in __init__
    s.bind(addr)
TypeError: an integer is required (got type str)
```

> NOTE: Debian testing (bullseye) has removed the "python" package and the '/usr/bin/python' symlink due to the deprecation of Python 2. No packaged scripts should depend on the existence of '/usr/bin/python': if they do, that is a bug that should be reported to Debian. You can use the 'python-is-python3' or 'python-is-python2' packages to restore an appropriate '/usr/bin/python' symlink for third-party or legacy scripts.
From: https://wiki.debian.org/Python

I've installed the "python-is-python3" package, since kiwicliend does not specify a python version and python2 is deprecated (pip2 is no longer available to install the required soundcard module).

kiwirecorder runs fine.

Thank you.

**Comment by rikvanriel** [comment]
I am using kiwiclientd with Python 3 in Fedora, but the exact Python version here is 3.6.

I can only guess that your Python version must be thinking that "port = 6400" is a string assignment, and not a number...

Which Python version are you using?

**Comment by helioshk** [comment]
Python 3.9.2

**Comment by helioshk** [comment]
It does say type='string' though?

```
**    group.add_option('--rigctl-port', '--rigctl-port',
                      dest='rigctl_port',
                      type='string', default='6400',**
```

**Comment by rikvanriel** [comment]
That option IS a string though, since it can contain a comma separated list of multiple port numbers.

Each specified port number is then cast to an int.

Could you try casting the port number to an int in each assignment of addr in rigctld.py like this?

diff --git a/kiwi/rigctld.py b/kiwi/rigctld.py
index 1bf8ab5f690a..da007edaf537 100644
--- a/kiwi/rigctld.py
+++ b/kiwi/rigctld.py
@@ -62,10 +62,10 @@ import select
 
         try:
             socket.inet_aton(ipaddr)
-            addr = (ipaddr, port)
+            addr = (ipaddr, (int)port)
             s = rigsocket(socket.AF_INET, socket.SOCK_STREAM)
         except socket.error:
-            addr = (ipaddr, port, 0, 0)
+            addr = (ipaddr, (int)port, 0, 0)
             s = rigsocket(socket.AF_INET6, socket.SOCK_STREAM)
 
         s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

**Comment by helioshk** [comment]
```
  File "/home/helios/git/kiwiclient/kiwi/rigctld.py", line 65
    addr = (ipaddr, (int)port)
                         ^
SyntaxError: invalid syntax
```

**Comment by rikvanriel** [comment]
Sorry, lets try that again :/

```
--- a/kiwi/rigctld.py
+++ b/kiwi/rigctld.py
@@ -62,10 +62,10 @@ import select
 
         try:
             socket.inet_aton(ipaddr)
-            addr = (ipaddr, port)
+            addr = (ipaddr, int(port))
             s = rigsocket(socket.AF_INET, socket.SOCK_STREAM)
         except socket.error:
-            addr = (ipaddr, port, 0, 0)
+            addr = (ipaddr, int(port), 0, 0)
             s = rigsocket(socket.AF_INET6, socket.SOCK_STREAM)
 
         s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

**Comment by helioshk** [comment]
I think now it tries to bind to port 6, if I understand correctly?
Sorry I'm no big help ...

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/helios/git/kiwiclient/kiwi/rigctld.py", line 75, in __init__
    s.bind(addr)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 427, in <module>
    main()
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 401, in main
    snd_recorders.append(KiwiWorker(args=(KiwiSoundRecorder(opt),opt,run_event)))
  File "/home/helios/git/kiwiclient/kiwi/worker.py", line 18, in __init__
    self._rigctld = Rigctld(self._recorder, self._options.rigctl_port, self._options.rigctl_address)
  File "/home/helios/git/kiwiclient/kiwi/rigctld.py", line 77, in __init__
    logging.error("could not bind to port ", port)
Message: 'could not bind to port '
Arguments: ('6',)
Traceback (most recent call last):
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 427, in <module>
    main()
  File "/home/helios/git/kiwiclient/./kiwiclientd.py", line 401, in main
    snd_recorders.append(KiwiWorker(args=(KiwiSoundRecorder(opt),opt,run_event)))
  File "/home/helios/git/kiwiclient/kiwi/worker.py", line 18, in __init__
    self._rigctld = Rigctld(self._recorder, self._options.rigctl_port, self._options.rigctl_address)
  File "/home/helios/git/kiwiclient/kiwi/rigctld.py", line 75, in __init__
    s.bind(addr)
PermissionError: [Errno 13] Permission denied

```

**Comment by rikvanriel** [comment]
Huh, so now it's casting the string 6400 to the int number 6?  Lets try casting it at an earlier time, since the port function argument already seems to be cast to int at an earlier stage, anyway...

```
--- a/kiwi/rigctld.py
+++ b/kiwi/rigctld.py
@@ -56,7 +56,7 @@ import select
         self._clientsockets = []
         # default localhost on port 6400
         if port == None:
-            port = 6400
+            port = int(6400)
         if ipaddr == None:
             ipaddr = "127.0.0.1" 
```

**Comment by helioshk** [comment]
The "6" seems to be coming from somewhere else.
Even if i have port = int(7777), still:
```
Message: 'could not bind to port '
Arguments: ('6',)
```

**Comment by jks-prv** [comment]
The changes from PR #81 I just merged includes the following which seems to fix this problem:
```
-                      type='string', default='6400',
+                      type='string', default=[6400],
```
