### ISSUE TITLE
kiwi_nc: do we need the writer part?

### ISSUE THREAD

**Issue by szpajder** [jks-prv/kiwiclient#92]
Thanks for merging my kiwi_nc PR. Now I have a question about this:

```
2021-11-14 23:28:18,131 pid 24617 a.b.c.d:8073 server closed the connection unexpectedly. Reconnecting after 5 seconds
```

This happens every 8-or-so seconds over and over again and is caused by the fact that kiwi_nc starts two instances of KiwiNetcat object:

```python
    for i,opt in enumerate(options):
        opt.multiple_connections = multiple_connections
        opt.idx = 0
        nc_inst.append(KiwiWorker(args=(KiwiNetcat(opt, True),opt,run_event)))
        opt.writer_init = False
        opt.idx = 1
        nc_inst.append(KiwiWorker(args=(KiwiNetcat(opt, False),opt,run_event)))
```

which spawns two receivers and hence two connections to the KiwiSDR:

```
2021-11-14 22:51:08,931 pid 24617 started sound recorder 0
2021-11-14 22:51:08,932 pid 24617 started sound recorder 1
```

The first one is for reading samples and this one works fine. The other one is a writer that waits for commands to be entered via stdin and sent to the server. However most Kiwis allow only one connection per IP address, so the second one gets dropped, kiwi_nc wants to reconnect, gets dropped again and so on. This floods the logs on the client and probably also on the server.

While I understand that the original netcat utility works in both directions (reading and writing), I'm not sure if the writing part has any purpose in kiwi_nc. Is there any use case for it? And if there is, how is it supposed to work, given that it needs two connections to the Kiwi? In order to be usable, it would need to be reworked somehow.

If there is no use case for this feature, I suggest removing it. I may file a PR for this.

**Comment by jks-prv** [comment]
Okay, I just PR'd a fix. One of the original ideas for kiwi_nc was as glue to sshd to allow secure admin connections to the Kiwi. The writer thread should have only been enabled when the `--admin` option was specified.

**Comment by szpajder** [comment]
Thanks! Works great now.
