### ISSUE TITLE
kiwirecorder and kiwiclilent support synchronous demodulation modes

### ISSUE THREAD

**Issue by lileswc** [jks-prv/kiwiclient#98]
Is there a reason that the code does not support the synchronous demodulation methods of synchronous am (sam), synchronous am upper sideband (sau) and synchronous am lower sideband (sal)? As I understand it these modes are supported by the BeagleBone on the kiwiSDR.

Are there any planes to support these modes in future?

Thank you
lileswc

**Comment by rikvanriel** [comment]
Thank you for pointing out this issue.

It looks like it was easy to fix by simply allowing these modulations to be passed through to the kiwisdr by kiwiclient. See the pull request below for the fix:

https://github.com/jks-prv/kiwiclient/pull/99

**Comment by lileswc** [comment]
Thank you.
Bill

**Comment by lileswc** [comment]
The mod works fine for synchronous am demod (sam). Thank you.  There is a slight problem with the upper and lower sideband modes. Those modes are still am modes but only process the upper sideband or lower sideband with the am carrier. So for sau  the value of lc should be zero so the demodulation routine can still synchronize with the carrier and for sal the value of hc should be 0 so the demodulation routine can still synchronize with the carrier.

I used the -L and -H options to set these values for sau and sal respectively and then the demodulation worked find. Thus the recommended defaults as listed above should work fine.

Thank you.

Bill

**Comment by jks-prv** [comment]
I'm working on a fix that supports all the current modes with their proper passband defaults.

**Comment by lileswc** [comment]
Thank you.
Bill
